config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get    '/signup',   to: 'customers#new'
  post   '/signup',   to: 'customers#create'
  get    '/login',    to: 'sessions#new'
  post   '/login',    to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: 'logout'

  resources :customers do
    resources :bookings do
      resources :cities
    end
  end

  resources :cleaners
  resources :cities
  root 'sessions#new'
end

#   get 'sessions/new'
#   post 'login' => 'sessions#create'
#   delete 'logout' => 'sessions#destroy'
#   get 'city/index'
#
#   resources :customers do
#     resources :cities do
#       resources :bookings
#     end
#   end
#
#   resources :customer do
#     get 'booking', to: 'customers#booking'
#     resources :bookings
#   end
#
#   resources :customers do
#     resources :bookings
#   end
#
#   resources :cleaners do
#     get 'cleaner_booking', to: 'cleaners#cleaner_booking'
#   end
#
#   resources :cities
#   root 'sessions#new'
# end

app/models/booking.rb
# frozen_string_literal: true

# main class
class Booking < ApplicationRecord
  belongs_to :customer
  belongs_to :cleaner
end

app/controllers/bookings_controller.rb
# frozen_string_literal: true

# booking class
class BookingsController < ApplicationController
  before_action :set_booking, only: %i[show edit update destroy]
  before_action :set_customer

  def index
    @customer = Customer.find(params[:customer_id])

    @bookings = @customer.bookings
    # @city = City.find(params[:city_id])
    # @bookings = @customer.bookings
    # @cleaner = Cleaner.find(params[:cleaner_id])
    # @cleaner  = Cleaner.find(params[:cleaner_id])
  end

  def show; end

  def new
    @booking = Booking.new
    @cleaners = Cleaner.all
  end

  def edit; end

  def create
    @booking = @customer.bookings.new(booking_params)
    # @customer = Customer.find(params[:customer_id])

    respond_to do |format|
      if @booking.save!
        format.html { redirect_to customer_bookings_path,
                                notice: 'Booking was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to @booking,
                                notice: 'Booking was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to bookings_url,
                              notice: 'Booking was successfully destroyed.' }
    end
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:customer_id, :cleaner_id, :date)
  end

  def set_customer
    @customer = Customer.find(params[:customer_id])
  end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_form.html.erb
<div>
  <%= form_with model: @booking, url: customer_bookings_path, local: true do |f| %>

    <div class="field">
      <%= f.label :date %><br>
      <%= f.date_field :date %><br><br>
    </div>

    <div class="btn dropdown">
        <%= f.label :Select_Cleaner %><br>
        <%= f.collection_select :cleaner_id, @cleaners, :id, :first_name %><br><br>
      <%= f.submit %>
    </div>  
  <% end %>
</div>

app/views/bookings/edit.html.erb
<h1>Editing Booking</h1>

<%= render 'form' %>

<%= link_to 'Show', @booking %> |
<%= link_to 'Back', bookings_path %>

app/views/bookings/index.html.erb
<p id="notice"><%= notice %></p>

<center><h1>Your Bookings</h1></center>
<%= link_to 'New Booking', new_customer_booking_path, class: "btn btn-primary" %><br><br>

<table class="table table-hover" width="10%">
    <tr>
      <th>Customer</th>
      <th>Cleaner</th>
      <th>Date</th>
    </tr>

    <% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.customer.first_name %></td>
        <td><%= booking.cleaner.first_name %></td>
        <td><%= booking.date %></td>
      </tr>
    <% end %>
</table>

app/views/bookings/new.html.erb
<h1>New Booking</h1>

<%= render 'form' %><br>

<%#= link_to 'Back', customers_path %>

app/views/bookings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @booking.date %>
</p>

<%= link_to 'Edit', edit_booking_path(@booking) %> |
<%= link_to 'Back', customers_path %>