config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get    '/signup',   to: 'customers#new'
  post   '/signup',   to: 'customers#create'
  get    '/login',    to: 'sessions#new'
  post   '/login',    to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: 'logout'

  resources :customers do
    resources :bookings do
      resources :cities
    end
  end

  resources :cleaners
  resources :cities
  root 'sessions#new'
end

#   get 'sessions/new'
#   post 'login' => 'sessions#create'
#   delete 'logout' => 'sessions#destroy'
#   get 'city/index'
#
#   resources :customers do
#     resources :cities do
#       resources :bookings
#     end
#   end
#
#   resources :customer do
#     get 'booking', to: 'customers#booking'
#     resources :bookings
#   end
#
#   resources :customers do
#     resources :bookings
#   end
#
#   resources :cleaners do
#     get 'cleaner_booking', to: 'cleaners#cleaner_booking'
#   end
#
#   resources :cities
#   root 'sessions#new'
# end

app/models/customer.rb
# frozen_string_literal: true

# main class
class Customer < ApplicationRecord
  has_many :bookings
  # has_one :city
  has_and_belongs_to_many :cities, join_table: 'customers_cities'
  validates :phone_number, uniqueness: true, length: { minimum: 10 }
  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/controllers/customers_controller.rb
# frozen_string_literal: true

# customer class
class CustomersController < ApplicationController
  before_action :set_customer, only: %i[show edit update destroy]

  def index
    current_customer = Customer.find_by_id(session[:current_customer_id])
    @customers = Customer.all
    @cities = City.all
    @booking = Booking.all
  end

  def show; end

  def new
    @customer = Customer.new
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html do
          redirect_to @customer,
                      notice: 'Customer was successfully created.'
        end
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html do
          redirect_to @customer,
                      notice: 'Customer was successfully updated.'
        end
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy
    redirect_to customers_url
    respond_to do |format|
      format.html do
        redirect_to @customer,
                    notice: 'Customer Destroyed.'
      end
    end
  end

  private

  def set_customer
    @customer = Customer.find(params[:id])
  end

  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :phone_number)
  end
end

app/helpers/customer_helper.rb
module CustomerHelper
end

app/views/customers/_form.html.erb
<%= provide(:update_text, 'Create Account') %>
<div class="row">
  <div class="col-md-4 col-md-offset-4">
<%= form_for(@customer) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

    <%= f.label :first_name %><br>
    <%= f.text_field :first_name, class: 'form-control' %><br><br>

    <%= f.label :last_name %><br>
    <%= f.text_field :last_name, class: 'form-control' %><br><br>

    <%= f.label :phone_number %><br>
    <%= f.text_field :phone_number, class: 'form-control' %><br><br>
    <center>
      <%= f.submit yield(:update_text), class: "btn btn-primary" %><br>
    <center>
<% end %>
  </div>
</div>

app/views/customers/edit.html.erb
<h1>Editing Customer</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer %>
<%#= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Customers</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Phone number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.first_name %></td>
        <td><%= customer.last_name %></td>
        <td><%= customer.phone_number %></td>
        <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Destroy' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/customers/new.html.erb
<%# provide(:title, 'Sign up') %>
<%# provide(:path, signup_path) %>
<center><h1>Sign up</h1></center>

<%= render 'form' %>

<!-- <h1>New Customer</h1> -->

<%#= render 'form' %>

<%#= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>
<table border="2">

  <tr>
    <th><strong>First name:</strong></th>
    <td><%= @customer.first_name %></td>
  </tr>

  <tr>
    <th><strong>Last name:</strong></th>
    <td><%= @customer.last_name %></td>
  </tr>

  <tr>
    <th><strong>Phone number:</strong></th>
    <td><%= @customer.phone_number %></td>
  </tr>

</table><br><br>

<%= link_to 'Edit', edit_customer_path(@customer), class: "btn btn-primary"%> |
<%#= link_to 'Back', root_path %>
<%= link_to 'Booking', customer_bookings_path(customer_id: @customer.id), class: "btn btn-primary" %> |

<%# if session[:customer_id] %>
  <%= link_to 'Logout', logout_path, :method => :delete, class: "btn btn-primary"	%>
<%# end %>