config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get    '/signup',   to: 'customers#new'
  post   '/signup',   to: 'customers#create'
  get    '/login',    to: 'sessions#new'
  post   '/login',    to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: 'logout'

  resources :customers do
    resources :bookings do
      resources :cities
    end
  end

  resources :cleaners
  resources :cities
  root 'sessions#new'
end

#   get 'sessions/new'
#   post 'login' => 'sessions#create'
#   delete 'logout' => 'sessions#destroy'
#   get 'city/index'
#
#   resources :customers do
#     resources :cities do
#       resources :bookings
#     end
#   end
#
#   resources :customer do
#     get 'booking', to: 'customers#booking'
#     resources :bookings
#   end
#
#   resources :customers do
#     resources :bookings
#   end
#
#   resources :cleaners do
#     get 'cleaner_booking', to: 'cleaners#cleaner_booking'
#   end
#
#   resources :cities
#   root 'sessions#new'
# end

app/models/city.rb
# frozen_string_literal: true

# main class
class City < ApplicationRecord
  has_and_belongs_to_many :cleaners, join_table: 'cities_cleaners'
end

app/controllers/cities_controller.rb
# frozen_string_literal: true

# cityclass
class CitiesController < ApplicationController
  def index
    @cities = City.all
  end

  def new
    @city = City.new
  end

  def create
    @city = City.new(city_params)
    @city.save
    redirect_to new_city_path
  end

  private

  def city_params
    params.require(:city).permit(:name)
  end
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/views/cities/index.html.erb
<h1>Select City</h1>
<table>
  <tr>
    <th>City Name</th>
    <th>Action</th>
  </tr>
  <% @cities.each do |city| %>
    <tr>
	     <td><%= city.name.upcase %></td>
       <td><%= link_to 'Booking', new_customer_city_booking_path(city_id: city.id)%></td>
    </tr>
<% end %></table>

app/views/cities/new.html.erb
<%= form_with model: @city, local: true do |c| %>
  <div>
    <%= c.label :city%><br>
    <%= c.text_field :name %>
  </div><br>
  <div>
    <%= c.submit %><br>
    <%= link_to 'Back', root_path%>
  </div>
<% end %>

app/views/cities/show.html.erb
<p>
  <strong>First name:</strong>
  <%= @customer.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @customer.last_name %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @customer.phone_number %>
</p>

<%= link_to 'Bookings', customer_cities_path(customer_id: @customer.id) %><br>
<%= link_to 'My booking', customer_my_booking_path(customer_id: @customer.id) %><br>

<%= link_to 'Edit', edit_customer_path(@customer) %><br>
<%= link_to 'Back', customers_path() %>