config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get    '/signup',   to: 'customers#new'
  post   '/signup',   to: 'customers#create'
  get    '/login',    to: 'sessions#new'
  post   '/login',    to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: 'logout'

  resources :customers do
    resources :bookings do
      resources :cities
    end
  end

  resources :cleaners
  resources :cities
  root 'sessions#new'
end

#   get 'sessions/new'
#   post 'login' => 'sessions#create'
#   delete 'logout' => 'sessions#destroy'
#   get 'city/index'
#
#   resources :customers do
#     resources :cities do
#       resources :bookings
#     end
#   end
#
#   resources :customer do
#     get 'booking', to: 'customers#booking'
#     resources :bookings
#   end
#
#   resources :customers do
#     resources :bookings
#   end
#
#   resources :cleaners do
#     get 'cleaner_booking', to: 'cleaners#cleaner_booking'
#   end
#
#   resources :cities
#   root 'sessions#new'
# end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "Login", login_path %></li>
      <li><%= link_to "Sign Up", signup_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Clean Work", "#" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <% if @customer logged_in %>
          <li><%= link_to "Customers", customers_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", customer_path %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
           <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all',
                                          'data-turbolinks-track': 'reload' %>
<%#= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CleanWork</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%#= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-primary bg-primary">
  <%#= link_to 'Bookings', bookings_path %>
  <%#= link_to 'Customers', customers_path %>

  <h3>
    <center>
      <%= link_to 'Clean Work', "#", class: "text-white bg-primary" %>
    </center>
  </h3>
<%#= link_to 'Cleaners', cleaners_path %>
</nav>


<%= yield %>

</body>
</html>